name: MacOS
on:
    workflow_dispatch:
    push:
      tags:
        - '*'

jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-13, macos-14]
        qt_ver: [5.15.2]
        qt_arch: [clang_64]
    env:
      targetName: hap_instaler
      BUILD_TYPE: Release

    steps:
      # 安装QT
      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: ${{ matrix.qt_ver }}
          cached: 'false'

      # 拉取代码
      - uses: actions/checkout@v4
        with:
          submodules: true
    
      # 构建
      - name: build macos
        run: |
          mkdir -p ${{github.workspace}}/build
          cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
          cd ${{github.workspace}}/build
          make
    
      # 打包
      - name: package
        run: |
          # 打包
          macdeployqt build/${targetName}.app -verbose=1
          # 拷贝依赖
          cp quazip/mac/libs/*.dylib build/${targetName}.app/Contents/Frameworks/
          install_name_tool -change "libquazip.1.dylib" "@rpath/libquazip.1.dylib" build/${targetName}.app/Contents/MacOS/hap_installer
          # 拷贝图标
          cp AppIcon.icns build/${targetName}.app/Contents/Resources/

      # 上传artifacts          
      - uses: actions/upload-artifact@v4
        with:
          name: ${{ env.targetName }}_${{ matrix.os }}_${{matrix.qt_ver}}.zip
          path: build/${{ env.targetName }}.app